### PR TITLE
put some order to the structure

### PR DESCRIPTION
**Pull request by biniamGere**
This change is to give the project a structure that will be built upon. At the moment we are keeping all the Components and Containers at the ```src``` directory which makes it messy, confusing and difficult to test as the project grows.   

@AranBacall, you will need to pull and merge carefully if you have made a lot of changes.

### CODE REVIEW

**Review by barnesca — COMMENTED** [review]
Putting the containers and components into their own packages helps. I'm not so sure about naming everything index.js though, is this standard? To me it seems more confusing to give most of the files the same name.

**Comment by biniamGere** [comment]
@barnesca it's just a naming convention with purpose of **clarifying responsibility** and **encapsulation** 

Scene -> container -> components -> component

Scene:-  is page/view which contains Container(s). in most cases have one container. by naming the container ```index.js```, we are specifying that ```index.js``` is the main container and we can import it just by pointing to the folder(since the class that is importing it doesn't need to know how this part is implemented).

Containers include one or more components. usually, we would have a main component that would include other components. for instance, you could have _HomeComponent_ which would include _formComponent_, _imageComponent_ e.t.c. now by naming the  _HomeComponent_  : ```index.js```, you are giving it the responsibility of controlling and managing the rest of the components. The container will have only the responsibility of managing the state with the help of reducer and knows nothing about the components .
 
Hope that's clear.

**Comment by barnesca** [comment]
Ah I see. Thanks for explaining it Biniam. It mostly makes sense to me and if that's the standard then the branch looks fine to commit.

**Comment by biniamGere** [comment]
thanks, @barnesca , but there are few conflicts created by recent merge that I have to resolve first.

**Pull request closed without merging**
